import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainerWrapper } from '../components/ToastContainerWrapper';
import { ClientWorks } from '../components/ClientWorks';
import { Header } from '../components/Header';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' data-theme='forest'>
      <body className={classNames(inter.className, 'min-w-[300px]')}>
        <Header />
        {children}
        <ToastContainerWrapper />
        <ClientWorks />
      </body>
    </html>
  );
}
